/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Core Design Tokens
        "primary": "#b52603",
        "primary-container": "#ff5a36",
        "primary-fixed": "#ffdad2",
        "primary-fixed-dim": "#ffb4a3",
        "on-primary": "#ffffff",
        "on-primary-container": "#5a0c00",
        "on-primary-fixed": "#3d0600",
        "on-primary-fixed-variant": "#8c1900",
        
        "secondary": "#615e57",
        "secondary-container": "#e7e2d9",
        "secondary-fixed": "#e7e2d9",
        "secondary-fixed-dim": "#cbc6bd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#67645d",
        "on-secondary-fixed": "#1d1b16",
        "on-secondary-fixed-variant": "#494640",
        
        "tertiary": "#006d30",
        "tertiary-container": "#43a55d",
        "tertiary-fixed": "#95f8a7",
        "tertiary-fixed-dim": "#79db8d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#003313",
        "on-tertiary-fixed": "#00210a",
        "on-tertiary-fixed-variant": "#005323",
        
        "surface": "#fff8f6",
        "surface-bright": "#fff8f6",
        "surface-dim": "#e4d7d2",
        "surface-variant": "#ede0db",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff1ec",
        "surface-container": "#f9ebe6",
        "surface-container-high": "#f3e5e0",
        "surface-container-highest": "#ede0db",
        "on-surface": "#211a17",
        "on-surface-variant": "#5b403a",
        "inverse-surface": "#362f2c",
        "inverse-on-surface": "#fceee9",
        "inverse-primary": "#ffb4a3",
        "outline": "#8f7069",
        "outline-variant": "#e3beb6",
        "background": "#fff8f6",
        "on-background": "#211a17",
        "surface-tint": "#b52603",
        
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        // Mature Edition Warm Tokens & Aliases
        "coral": "#FF5A36",
        "coral-hover": "#e44e2c",
        "coral-subtle": "#FFF0ED",
        "cream": "#FCFAF5",
        "sand": "#F2ECE1",
        "sand-border": "#E4DCD0",
        "sand-light": "#FAF6EE",
        "charcoal": "#2E2724",
        "charcoal-muted": "#6E645F",
        "charcoal-light": "#968A82",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.25rem",
        "gutter": "1rem",
        "margin": "1.25rem",
      },
      fontFamily: {
        sans: ["Manrope", "Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Manrope", "Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Manrope", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Manrope", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Manrope", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Manrope", "Plus Jakarta Sans", "sans-serif"],
        "title-editorial": ["Newsreader", "serif"],
        "body-editorial-italic": ["Newsreader", "serif"],
        "body-lg": ["DM Sans", "Inter", "sans-serif"],
        "body-md": ["DM Sans", "Inter", "sans-serif"],
        "body-sm": ["DM Sans", "Inter", "sans-serif"],
        "label-lg": ["DM Sans", "Inter", "sans-serif"],
        "label-md": ["DM Sans", "Inter", "sans-serif"],
        "label-sm": ["DM Sans", "Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-editorial": ["20px", { lineHeight: "28px", letterSpacing: "0.0em", fontWeight: "400" }],
        "body-editorial-italic": ["15px", { lineHeight: "22px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0.0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
