"""Phase 2 data-layer tests: datetime columns, audit fields, indexes,
migrations."""

import time
import uuid
from datetime import datetime, timedelta
from pathlib import Path

from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlmodel import Session, select

from app.database import engine, init_db
from app.models import Experience, Guide, GuideRequest, ItineraryStop, User, UserSession
from app.services.auth import create_session, resolve_user
from app.timeutil import utcnow


def setup_module(module):
    init_db()


def _experience(name: str) -> Experience:
    return Experience(
        name=name,
        category="food",
        lat=19.05,
        lng=72.82,
        avg_cost=100,
        duration_min=60,
        rating=4.0,
        description="t",
        tags=[],
        accessibility_flags=[],
    )


def test_timestamps_auto_populate_and_touch_on_update():
    with Session(engine) as s:
        exp = _experience(f"TS-{uuid.uuid4().hex[:6]}")
        s.add(exp)
        s.commit()
        s.refresh(exp)

        assert isinstance(exp.created_at, datetime)
        assert isinstance(exp.updated_at, datetime)
        created = exp.created_at

        time.sleep(0.02)
        exp.rating = 4.9
        s.add(exp)
        s.commit()
        s.refresh(exp)

        assert exp.created_at == created, "created_at must not change"
        assert exp.updated_at > created, "updated_at must advance on update"


def test_composite_indexes_registered():
    def names(model):
        return {index.name for index in model.__table__.indexes}

    assert "ix_experiences_category_rating" in names(Experience)
    assert "ix_experiences_lat_lng" in names(Experience)
    assert "ix_guides_experience_rating" in names(Guide)
    assert "ix_guide_requests_user_created" in names(GuideRequest)
    assert "ix_user_sessions_user_expires" in names(UserSession)
    assert "ix_itinerary_stops_itinerary_seq" in names(ItineraryStop)


def test_session_expiry_uses_datetime():
    with Session(engine) as s:
        user = User(name="P2", email=f"p2-{uuid.uuid4().hex[:8]}@localiq.test", password_hash="x")
        s.add(user)
        s.commit()
        s.refresh(user)

        token, expires_at, created = create_session(user.id, s)
        assert isinstance(expires_at, datetime)
        assert isinstance(created, datetime)
        assert resolve_user(token, s) is not None

        row = s.exec(select(UserSession).where(UserSession.user_id == user.id)).first()
        assert row is not None and isinstance(row.expires_at, datetime)
        row.expires_at = utcnow() - timedelta(minutes=1)
        s.add(row)
        s.commit()

        assert resolve_user(token, s) is None, "expired session must be rejected"


def test_guide_request_stores_datetime_created_at():
    with Session(engine) as s:
        guide = s.exec(select(Guide)).first()
        assert guide is not None
        row = GuideRequest(guide_id=guide.id, booking_ref=f"P2-{uuid.uuid4().hex[:4].upper()}")
        s.add(row)
        s.commit()
        s.refresh(row)
        assert isinstance(row.created_at, datetime)


def test_alembic_has_single_head():
    root = Path(__file__).resolve().parent.parent
    config = Config(str(root / "alembic.ini"))
    config.set_main_option("script_location", str(root / "alembic"))
    script = ScriptDirectory.from_config(config)
    assert len(script.get_heads()) == 1


def test_migrations_match_models(tmp_path, monkeypatch):
    """A fresh migration must reproduce the models exactly (no drift)."""
    import os

    from alembic import command

    from app.config import get_settings

    root = Path(__file__).resolve().parent.parent
    config = Config(str(root / "alembic.ini"))
    config.set_main_option("script_location", str(root / "alembic"))

    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path / 'drift.db'}")
    get_settings.cache_clear()
    try:
        command.upgrade(config, "head")
        # Raises AutogenerateDiffsDetected when the DB and models diverge.
        command.check(config)
    finally:
        get_settings.cache_clear()
        os.environ.pop("DATABASE_URL", None)
        get_settings.cache_clear()
