"""guide onboarding documents and specialisation

Revision ID: 07f36c4053d8
Revises: 2257ca36aed2
Create Date: 2026-09-26 23:34:34.074177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '07f36c4053d8'
down_revision: Union[str, None] = '2257ca36aed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guide_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_license_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
        batch_op.add_column(sa.Column('guide_license_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
        batch_op.add_column(sa.Column('specialization_areas', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('niches', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('documents_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guide_profiles', schema=None) as batch_op:
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('documents_json')
        batch_op.drop_column('niches')
        batch_op.drop_column('specialization_areas')
        batch_op.drop_column('guide_license_key')
        batch_op.drop_column('driver_license_key')

    # ### end Alembic commands ###
