"""onboarding sessions

Revision ID: 2257ca36aed2
Revises: a9bf2609c1cf
Create Date: 2026-09-26 23:31:50.265057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2257ca36aed2'
down_revision: Union[str, None] = 'a9bf2609c1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('messages_json', sa.JSON(), nullable=True),
    sa.Column('answers_json', sa.JSON(), nullable=True),
    sa.Column('extracted_json', sa.JSON(), nullable=True),
    sa.Column('completed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_sessions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboarding_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboarding_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_onboarding_sessions_user_kind', ['user_id', 'kind', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_onboarding_sessions_user_kind')
        batch_op.drop_index(batch_op.f('ix_onboarding_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_onboarding_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_onboarding_sessions_kind'))

    op.drop_table('onboarding_sessions')
    # ### end Alembic commands ###
