"""personalization taste signals interactions agent

Revision ID: 279a5a0ecfc2
Revises: 61b45b1df92d
Create Date: 2026-09-26 19:32:16.124880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '279a5a0ecfc2'
down_revision: Union[str, None] = '61b45b1df92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('messages_json', sa.JSON(), nullable=True),
    sa.Column('state_json', sa.JSON(), nullable=True),
    sa.Column('last_active_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_conversation_sessions_user_active', ['user_id', 'last_active_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('preference_signals',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preference_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preference_signals_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index('ix_preference_signals_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_preference_signals_user_id'), ['user_id'], unique=False)

    op.create_table('user_activity_interactions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activity_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activity_interactions_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index('ix_user_activity_interactions_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_interactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taste_profile_text', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
        batch_op.add_column(sa.Column('taste_profile_vector', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('personalization_enabled', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False, server_default='en'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('personalization_enabled')
        batch_op.drop_column('taste_profile_vector')
        batch_op.drop_column('taste_profile_text')

    with op.batch_alter_table('user_activity_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_interactions_user_id'))
        batch_op.drop_index('ix_user_activity_interactions_user_created')
        batch_op.drop_index(batch_op.f('ix_user_activity_interactions_experience_id'))

    op.drop_table('user_activity_interactions')
    with op.batch_alter_table('preference_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preference_signals_user_id'))
        batch_op.drop_index('ix_preference_signals_user_created')
        batch_op.drop_index(batch_op.f('ix_preference_signals_experience_id'))

    op.drop_table('preference_signals')
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_user_id'))
        batch_op.drop_index('ix_conversation_sessions_user_active')

    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
