"""experience wallet passport badges logs

Revision ID: 35c8b298706a
Revises: a4d839e5231e
Create Date: 2026-09-26 22:43:15.604534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '35c8b298706a'
down_revision: Union[str, None] = 'a4d839e5231e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_logs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'experience_id', name='uq_experience_log_user_experience')
    )
    with op.batch_alter_table('experience_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_logs_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index('ix_experience_logs_user_completed', ['user_id', 'completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_logs_user_id'), ['user_id'], unique=False)

    op.create_table('experience_wallets',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_experiences', sa.Integer(), nullable=False),
    sa.Column('hidden_gem_count', sa.Integer(), nullable=False),
    sa.Column('total_spent_inr', sa.Integer(), nullable=False),
    sa.Column('total_duration_min', sa.Integer(), nullable=False),
    sa.Column('categories_json', sa.JSON(), nullable=True),
    sa.Column('cities_visited_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experience_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_wallets_user_id'), ['user_id'], unique=True)

    op.create_table('user_badges',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_code', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('earned_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_code', name='uq_user_badge_code')
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badges_badge_code'), ['badge_code'], unique=False)
        batch_op.create_index('ix_user_badges_user_earned', ['user_id', 'earned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))
        batch_op.drop_index('ix_user_badges_user_earned')
        batch_op.drop_index(batch_op.f('ix_user_badges_badge_code'))

    op.drop_table('user_badges')
    with op.batch_alter_table('experience_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experience_wallets_user_id'))

    op.drop_table('experience_wallets')
    with op.batch_alter_table('experience_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experience_logs_user_id'))
        batch_op.drop_index('ix_experience_logs_user_completed')
        batch_op.drop_index(batch_op.f('ix_experience_logs_experience_id'))

    op.drop_table('experience_logs')
    # ### end Alembic commands ###
