"""experience image key for self-hosted media

Revision ID: 4c167a25be1c
Revises: 86a251e9628c
Create Date: 2026-09-26 22:34:26.008499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c167a25be1c'
down_revision: Union[str, None] = '86a251e9628c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('image_key')

    # ### end Alembic commands ###
