"""phase4 semantic tags guides discovery

Revision ID: 61b45b1df92d
Revises: f7b3c4d50a16
Create Date: 2026-09-26 18:59:08.562975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.vector  # noqa: F401  (Vector type for embedding columns)


# revision identifiers, used by Alembic.
revision: str = '61b45b1df92d'
down_revision: Union[str, None] = 'f7b3c4d50a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composite_tags',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('required_tags', sa.JSON(), nullable=True),
    sa.Column('optional_tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('composite_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_composite_tags_name'), ['name'], unique=True)

    op.create_table('discovery_sources',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('last_scraped', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_sources_name'), ['name'], unique=False)

    op.create_table('tags',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('facet_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_category'), ['category'], unique=False)
        batch_op.create_index('ix_tags_facet_type', ['facet_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('experience_tags',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'tag_id', name='uq_experience_tag')
    )
    with op.batch_alter_table('experience_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_tags_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index('ix_experience_tags_tag', ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('scraped_candidates',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('llm_confidence', sa.Float(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('authenticity_signals', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('reviewed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraped_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_scraped_candidates_status', ['status'], unique=False)

    op.create_table('user_profiles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('home_location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('preferred_languages', sa.JSON(), nullable=True),
    sa.Column('travel_style', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('candidate_citations',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('quote', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('mention_date', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['scraped_candidates.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['discovery_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_citations_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index('ix_candidate_citations_candidate_source', ['candidate_id', 'source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_citations_source_id'), ['source_id'], unique=False)

    op.create_table('guide_packages',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('pickup_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('default_pickup_area', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('drop_off_same_as_pickup', sa.Boolean(), nullable=False),
    sa.Column('max_pickup_distance_km', sa.Float(), nullable=False),
    sa.Column('total_duration_hours', sa.Float(), nullable=False),
    sa.Column('inclusions', sa.JSON(), nullable=True),
    sa.Column('price_per_person', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('max_group_size', sa.Integer(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('cancellation_policy', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guide_packages', schema=None) as batch_op:
        batch_op.create_index('ix_guide_packages_guide', ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_packages_guide_id'), ['guide_id'], unique=False)

    op.create_table('user_interests',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'tag_name', name='uq_profile_interest')
    )
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_interests_profile_id'), ['profile_id'], unique=False)

    op.create_table('guide_package_stops',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('segment_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('location_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('travel_time_min', sa.Integer(), nullable=False),
    sa.Column('guide_notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['guide_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guide_package_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_package_stops_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_package_stops_package_id'), ['package_id'], unique=False)
        batch_op.create_index('ix_guide_package_stops_package_seq', ['package_id', 'sequence'], unique=False)

    op.create_table('package_bookings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_ref', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('pickup_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('guest_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('guest_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['guide_packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_bookings_booking_ref'), ['booking_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_bookings_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_bookings_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_bookings_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_bookings_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_package_bookings_user_status', ['user_id', 'status'], unique=False)

    op.create_table('package_reviews',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['package_bookings.id'], ),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['guide_packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_reviews_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index('ix_package_reviews_guide', ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_reviews_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_reviews_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_reviews_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', app.vector.Vector(), nullable=True))
        batch_op.add_column(sa.Column('vibe_vector', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('weather_suitability_score', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('accessibility_score', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('authenticity_score', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('safety_score', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('crowd_density_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='MEDIUM'))
        batch_op.add_column(sa.Column('noise_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='MODERATE'))
        batch_op.add_column(sa.Column('opening_hours_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('peak_times_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('best_visit_time', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
        batch_op.add_column(sa.Column('time_to_spend', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))

    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='unverified'))
        batch_op.add_column(sa.Column('background_checked', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('uin', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
        batch_op.add_column(sa.Column('areas_covered', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('energy_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='relaxed'))
        batch_op.add_column(sa.Column('storytelling_style', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False, server_default='casual'))
        batch_op.add_column(sa.Column('max_group_size', sa.Integer(), nullable=False, server_default='6'))
        batch_op.add_column(sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_verification_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='unverified'))
        batch_op.add_column(sa.Column('id_verified_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('kyc_provider_ref', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('kyc_provider_ref')
        batch_op.drop_column('id_verified_at')
        batch_op.drop_column('id_verification_status')

    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('max_group_size')
        batch_op.drop_column('storytelling_style')
        batch_op.drop_column('energy_level')
        batch_op.drop_column('areas_covered')
        batch_op.drop_column('uin')
        batch_op.drop_column('background_checked')
        batch_op.drop_column('verification_status')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('time_to_spend')
        batch_op.drop_column('best_visit_time')
        batch_op.drop_column('peak_times_json')
        batch_op.drop_column('opening_hours_json')
        batch_op.drop_column('noise_level')
        batch_op.drop_column('crowd_density_level')
        batch_op.drop_column('safety_score')
        batch_op.drop_column('authenticity_score')
        batch_op.drop_column('accessibility_score')
        batch_op.drop_column('weather_suitability_score')
        batch_op.drop_column('vibe_vector')
        batch_op.drop_column('embedding')

    with op.batch_alter_table('package_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_package_reviews_package_id'))
        batch_op.drop_index(batch_op.f('ix_package_reviews_guide_id'))
        batch_op.drop_index('ix_package_reviews_guide')
        batch_op.drop_index(batch_op.f('ix_package_reviews_booking_id'))

    op.drop_table('package_reviews')
    with op.batch_alter_table('package_bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_package_bookings_user_status')
        batch_op.drop_index(batch_op.f('ix_package_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_package_bookings_package_id'))
        batch_op.drop_index(batch_op.f('ix_package_bookings_guide_id'))
        batch_op.drop_index(batch_op.f('ix_package_bookings_experience_id'))
        batch_op.drop_index(batch_op.f('ix_package_bookings_booking_ref'))

    op.drop_table('package_bookings')
    with op.batch_alter_table('guide_package_stops', schema=None) as batch_op:
        batch_op.drop_index('ix_guide_package_stops_package_seq')
        batch_op.drop_index(batch_op.f('ix_guide_package_stops_package_id'))
        batch_op.drop_index(batch_op.f('ix_guide_package_stops_experience_id'))

    op.drop_table('guide_package_stops')
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_interests_profile_id'))

    op.drop_table('user_interests')
    with op.batch_alter_table('guide_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_packages_guide_id'))
        batch_op.drop_index('ix_guide_packages_guide')

    op.drop_table('guide_packages')
    with op.batch_alter_table('candidate_citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_citations_source_id'))
        batch_op.drop_index('ix_candidate_citations_candidate_source')
        batch_op.drop_index(batch_op.f('ix_candidate_citations_candidate_id'))

    op.drop_table('candidate_citations')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('scraped_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_scraped_candidates_status')

    op.drop_table('scraped_candidates')
    with op.batch_alter_table('experience_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experience_tags_tag_id'))
        batch_op.drop_index('ix_experience_tags_tag')
        batch_op.drop_index(batch_op.f('ix_experience_tags_experience_id'))

    op.drop_table('experience_tags')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index('ix_tags_facet_type')
        batch_op.drop_index(batch_op.f('ix_tags_category'))

    op.drop_table('tags')
    with op.batch_alter_table('discovery_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_sources_name'))

    op.drop_table('discovery_sources')
    with op.batch_alter_table('composite_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_composite_tags_name'))

    op.drop_table('composite_tags')
    # ### end Alembic commands ###
