"""add avg_cost index

Revision ID: 78ae6478570f
Revises: d83d02231eb3
Create Date: 2026-09-26 14:20:07.893663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ae6478570f'
down_revision: Union[str, None] = 'd83d02231eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index('ix_experiences_avg_cost', ['avg_cost'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('ix_experiences_avg_cost')

    # ### end Alembic commands ###
