"""itinerary planner share token and taste actions

Revision ID: 86a251e9628c
Revises: 279a5a0ecfc2
Create Date: 2026-09-26 20:04:50.274870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86a251e9628c'
down_revision: Union[str, None] = '279a5a0ecfc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_itineraries_share_token'), ['share_token'], unique=False)

    with op.batch_alter_table('user_activity_interactions', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_interactions', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itineraries_share_token'))
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
