"""right now engine live context fields

Revision ID: a4d839e5231e
Revises: 4c167a25be1c
Create Date: 2026-09-26 22:39:04.276831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4d839e5231e'
down_revision: Union[str, None] = '4c167a25be1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('right_now_score', sa.Float(), nullable=False, server_default=sa.text('50.0')))
        batch_op.add_column(sa.Column('right_now_context_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('right_now_updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('right_now_updated_at')
        batch_op.drop_column('right_now_context_json')
        batch_op.drop_column('right_now_score')

    # ### end Alembic commands ###
