"""app account fields and refresh tokens

Revision ID: a9bf2609c1cf
Revises: fc580f9e7648
Create Date: 2026-09-26 23:15:16.438288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9bf2609c1cf'
down_revision: Union[str, None] = 'fc580f9e7648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('refresh_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default=sa.text("'email'")))
        batch_op.add_column(sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default=sa.text("'free'")))
        batch_op.add_column(sa.Column('home_city', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False, server_default=sa.text("'Mumbai'")))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('home_city')
        batch_op.drop_column('tier')
        batch_op.drop_column('provider')

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_refresh_token_hash'))
        batch_op.drop_column('refresh_expires_at')
        batch_op.drop_column('refresh_token_hash')

    # ### end Alembic commands ###
