"""itinerary owner, favorites, feedback

Revision ID: bca4f9c535f1
Revises: 78ae6478570f
Create Date: 2026-09-26 14:28:31.924205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bca4f9c535f1'
down_revision: Union[str, None] = '78ae6478570f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'experience_id', name='uq_favorite_user_experience')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index('ix_favorites_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('recommendation_feedback',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_feedback_experience_created', ['experience_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_feedback_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_feedback_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_itineraries_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_itineraries_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_itineraries_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_itineraries_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_itineraries_user_id'))
        batch_op.drop_index('ix_itineraries_user_created')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('recommendation_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_feedback_experience_id'))
        batch_op.drop_index('ix_feedback_experience_created')

    op.drop_table('recommendation_feedback')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index('ix_favorites_user_created')
        batch_op.drop_index(batch_op.f('ix_favorites_experience_id'))

    op.drop_table('favorites')
    # ### end Alembic commands ###
