"""driver trip pickup drop and location

Revision ID: c0d966f82273
Revises: 07f36c4053d8
Create Date: 2026-09-26 23:50:35.730008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c0d966f82273'
down_revision: Union[str, None] = '07f36c4053d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drop_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
        batch_op.add_column(sa.Column('drop_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('drop_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('driver_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('driver_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('driver_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_bookings', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('driver_updated_at')
        batch_op.drop_column('driver_lng')
        batch_op.drop_column('driver_lat')
        batch_op.drop_column('drop_lng')
        batch_op.drop_column('drop_lat')
        batch_op.drop_column('drop_address')

    # ### end Alembic commands ###
