"""initial schema

Revision ID: d83d02231eb3
Revises: 
Create Date: 2026-09-26 14:04:54.077337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd83d02231eb3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('open_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('close_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('accessibility_flags', sa.JSON(), nullable=True),
    sa.Column('indoor_outdoor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_gem_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_category'), ['category'], unique=False)
        batch_op.create_index('ix_experiences_category_rating', ['category', 'rating'], unique=False)
        batch_op.create_index('ix_experiences_lat_lng', ['lat', 'lng'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_name'), ['name'], unique=False)

    op.create_table('itineraries',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_duration_min', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    op.create_table('guides',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('specialty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate_per_hour', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guides_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index('ix_guides_experience_rating', ['experience_id', 'rating'], unique=False)

    op.create_table('itinerary_stops',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('travel_time_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itinerary_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_stops_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itinerary_stops_itinerary_id'), ['itinerary_id'], unique=False)
        batch_op.create_index('ix_itinerary_stops_itinerary_seq', ['itinerary_id', 'sequence'], unique=False)

    op.create_table('user_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_user_sessions_user_expires', ['user_id', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('guide_requests',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('requester_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('booking_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guide_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_requests_booking_ref'), ['booking_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_requests_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_requests_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index('ix_guide_requests_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guide_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_requests_user_id'))
        batch_op.drop_index('ix_guide_requests_user_created')
        batch_op.drop_index(batch_op.f('ix_guide_requests_guide_id'))
        batch_op.drop_index(batch_op.f('ix_guide_requests_experience_id'))
        batch_op.drop_index(batch_op.f('ix_guide_requests_booking_ref'))

    op.drop_table('guide_requests')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index('ix_user_sessions_user_expires')
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('itinerary_stops', schema=None) as batch_op:
        batch_op.drop_index('ix_itinerary_stops_itinerary_seq')
        batch_op.drop_index(batch_op.f('ix_itinerary_stops_itinerary_id'))
        batch_op.drop_index(batch_op.f('ix_itinerary_stops_experience_id'))

    op.drop_table('itinerary_stops')
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.drop_index('ix_guides_experience_rating')
        batch_op.drop_index(batch_op.f('ix_guides_experience_id'))

    op.drop_table('guides')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('itineraries')
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiences_name'))
        batch_op.drop_index('ix_experiences_lat_lng')
        batch_op.drop_index('ix_experiences_category_rating')
        batch_op.drop_index(batch_op.f('ix_experiences_category'))

    op.drop_table('experiences')
    # ### end Alembic commands ###
