"""ai experience director sessions and tips

Revision ID: fc580f9e7648
Revises: 35c8b298706a
Create Date: 2026-09-26 22:49:18.954037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc580f9e7648'
down_revision: Union[str, None] = '35c8b298706a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tips',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message_text', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('location_trigger_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_tips', schema=None) as batch_op:
        batch_op.create_index('ix_ai_tips_experience_category', ['experience_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tips_experience_id'), ['experience_id'], unique=False)

    op.create_table('experience_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('end_time', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('route_json', sa.JSON(), nullable=True),
    sa.Column('live_context_json', sa.JSON(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experience_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_sessions_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_sessions_itinerary_id'), ['itinerary_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_experience_sessions_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_experience_sessions_user_status')
        batch_op.drop_index(batch_op.f('ix_experience_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_experience_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_experience_sessions_itinerary_id'))
        batch_op.drop_index(batch_op.f('ix_experience_sessions_experience_id'))

    op.drop_table('experience_sessions')
    with op.batch_alter_table('ai_tips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_tips_experience_id'))
        batch_op.drop_index('ix_ai_tips_experience_category')

    op.drop_table('ai_tips')
    # ### end Alembic commands ###
