# Pull the native Google Maps keys out of the backend env and wire them into the
# Flutter native projects. Web builds need no key: the app reads it from
# GET /api/v1/config at runtime.
#
# Usage: scripts\set-maps-keys.ps1 [-EnvFile backend\.env]

param(
    [string]$EnvFile = (Join-Path $PSScriptRoot "..\backend\.env")
)

$ErrorActionPreference = "Stop"
$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$appDir = Join-Path $root "frontend_flutter"

if (-not (Test-Path -LiteralPath $EnvFile)) {
    Write-Error "No env file at $EnvFile - copy backend\.env.example to backend\.env first."
}

function Get-EnvValue([string]$Name) {
    $line = Select-String -LiteralPath $EnvFile -Pattern "^$Name=" -ErrorAction SilentlyContinue |
        Select-Object -Last 1
    if ($null -eq $line) { return "" }
    return ($line.Line -replace "^$Name=", "").Trim().Trim('"')
}

$androidKey = Get-EnvValue "GOOGLE_MAPS_API_KEY_ANDROID"
$iosKey = Get-EnvValue "GOOGLE_MAPS_API_KEY_IOS"

if ([string]::IsNullOrWhiteSpace($androidKey)) {
    Write-Warning "GOOGLE_MAPS_API_KEY_ANDROID is empty in $EnvFile"
}

# Gradle reads GOOGLE_MAPS_API_KEY from the environment (build.gradle.kts).
$env:GOOGLE_MAPS_API_KEY = $androidKey
Write-Output "GOOGLE_MAPS_API_KEY set for Gradle (android/app)."

# iOS: build setting consumed by Info.plist via $(GOOGLE_MAPS_API_KEY).
if (-not [string]::IsNullOrWhiteSpace($iosKey)) {
    $target = Join-Path $appDir "ios\Flutter\Maps.xcconfig"
    Set-Content -LiteralPath $target -Value @(
        "// Generated by scripts\set-maps-keys.ps1 - git-ignored, never commit.",
        "GOOGLE_MAPS_API_KEY = $iosKey"
    )
    Write-Output "Wrote $target"
}

Write-Output "Done. Web builds need no key: the app reads it from /api/v1/config."
