#!/bin/bash
# Pull the native Google Maps keys out of the backend env and wire them into the
# Flutter native projects. The backend stays the single source of truth; the web
# key is never written to disk here because browsers get it from
# GET /api/v1/config at runtime.
#
# Usage: scripts/set-maps-keys.sh [path/to/env]   (default: backend/.env)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${1:-$ROOT/backend/.env}"
APP_DIR="$ROOT/frontend_flutter"

if [ ! -f "$ENV_FILE" ]; then
  echo "No env file at $ENV_FILE - copy backend/.env.example to backend/.env first." >&2
  exit 1
fi

read_key() {
  sed -n "s/^$1=//p" "$ENV_FILE" | tail -n 1 | tr -d '\r"'
}

ANDROID_KEY="$(read_key GOOGLE_MAPS_API_KEY_ANDROID)"
IOS_KEY="$(read_key GOOGLE_MAPS_API_KEY_IOS)"

if [ -z "$ANDROID_KEY" ]; then
  echo "GOOGLE_MAPS_API_KEY_ANDROID is empty in $ENV_FILE" >&2
fi

# Android: gradle picks the key up from the environment (see
# android/app/build.gradle.kts manifestPlaceholders) or from -PGOOGLE_MAPS_API_KEY.
export GOOGLE_MAPS_API_KEY="$ANDROID_KEY"
echo "GOOGLE_MAPS_API_KEY set for Gradle (android/app)."

# iOS: build setting consumed by Info.plist via $(GOOGLE_MAPS_API_KEY).
if [ -n "$IOS_KEY" ]; then
  mkdir -p "$APP_DIR/ios/Flutter"
  printf '// Generated by scripts/set-maps-keys.sh - git-ignored, never commit.\nGOOGLE_MAPS_API_KEY = %s\n' \
    "$IOS_KEY" > "$APP_DIR/ios/Flutter/Maps.xcconfig"
  echo "Wrote $APP_DIR/ios/Flutter/Maps.xcconfig"
fi

echo "Done. Web builds need no key: the app reads it from /api/v1/config."
